# 本项目下的dataset中的数据集仅供大家参考存放格式和调试代码是否能跑通
# dataset path
path: /home_ext/zjw/1_CODES/YOLO/YOLO/
train: ./dataset/mimicry_20260121/images/train  # path + train
val: ./dataset/mimicry_20260121/images/val # path + val
# test: ./dataset/mimicry_20260113/images/test # path + test

# number of classes
nc: 3

# class names
names: ['Hand', 'Pad_Glass', 'Phone_Glass']